// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Antonio Paya Gonzalez",
            "url": "http://antoniopg.tk",
            "email": "antonioalfa22@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/antonioalfa22/bms-monitoring/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dashboard/finding-type-count/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get finding type count by Project ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Findings By Project Dashboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/findings": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get findings by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Get findings by query",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "project_id",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "risk_description",
                        "name": "risk_description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "cwe",
                        "name": "cwe",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "line",
                        "name": "line",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "file_path",
                        "name": "file_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "vuln_id_from_tool",
                        "name": "vuln_id_from_tool",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "unique_id_from_tool",
                        "name": "unique_id_from_tool",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "mitigation",
                        "name": "mitigation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "impact",
                        "name": "impact",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "reference",
                        "name": "reference",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "active",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "dynamic_finding",
                        "name": "dynamic_finding",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "duplicate",
                        "name": "duplicate",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "risk_accepted",
                        "name": "risk_accepted",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "static_finding",
                        "name": "static_finding",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create finding",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Create finding",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Finding"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/findings/count": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Count findings by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Count findings by query",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "project_id",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "risk_description",
                        "name": "risk_description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "cwe",
                        "name": "cwe",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "line",
                        "name": "line",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "file_path",
                        "name": "file_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "vuln_id_from_tool",
                        "name": "vuln_id_from_tool",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "unique_id_from_tool",
                        "name": "unique_id_from_tool",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "mitigation",
                        "name": "mitigation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "impact",
                        "name": "impact",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "reference",
                        "name": "reference",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "reviewer",
                        "name": "reviewer",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "active",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "dynamic_finding",
                        "name": "dynamic_finding",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "duplicate",
                        "name": "duplicate",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "risk_accepted",
                        "name": "risk_accepted",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "static_finding",
                        "name": "static_finding",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/findings/parent": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get findings by query parent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Get findings by query parent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "parent_id",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "parent_type",
                        "name": "parent_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/findings/parent/count": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Count findings by query parent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Count findings by query parent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "parent_id",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "parent_type",
                        "name": "parent_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/findings/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get finding by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Get finding by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update finding by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Update finding by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Finding"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete finding by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finding"
                ],
                "summary": "Delete finding by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/import": {
            "post": {
                "description": "Upload a file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Import Test Result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline run ID from Repo",
                        "name": "pipeline_run_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline run URL from Repo",
                        "name": "pipeline_run_url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Commit hash",
                        "name": "commit_hash",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Branch name",
                        "name": "branch_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tool name",
                        "name": "tool_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Test title",
                        "name": "test_title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service key",
                        "name": "service_key",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_err.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http_err.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/pipeline-evaluations": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get pipeline evaluations by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Get pipeline evaluations by query",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "severity_critical_score",
                        "name": "severity_critical_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_high_score",
                        "name": "severity_high_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_medium_score",
                        "name": "severity_medium_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_low_score",
                        "name": "severity_low_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "threshold_score",
                        "name": "threshold_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create pipeline evaluation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Create pipeline evaluation",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.PipelineEvaluation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/pipeline-evaluations/count": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Count pipeline evaluations by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Count pipeline evaluations by query",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "severity_critical_score",
                        "name": "severity_critical_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_high_score",
                        "name": "severity_high_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_medium_score",
                        "name": "severity_medium_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "severity_low_score",
                        "name": "severity_low_score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "threshold_score",
                        "name": "threshold_score",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/pipeline-evaluations/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get pipeline evaluation by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Get pipeline evaluation by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update pipeline evaluation by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Update pipeline evaluation by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.PipelineEvaluation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete pipeline evaluation by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineEvaluation"
                ],
                "summary": "Delete pipeline evaluation by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get pipeline runs by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Get pipeline runs by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "branch_name",
                        "name": "branch_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "commit_hash",
                        "name": "commit_hash",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "project_id",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pipeline_run_url",
                        "name": "pipeline_run_url",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pipeline_run_id",
                        "name": "pipeline_run_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create pipeline run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Create pipeline run",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.PipelineRun"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/evaluate": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Evaluate pipeline run by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Evaluate pipeline run by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pipeline run ID from Repo",
                        "name": "pipeline_run_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Latest Evaluation Request ?",
                        "name": "latest_request",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get pipeline run by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Get pipeline run by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update pipeline run by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Update pipeline run by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.PipelineRun"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete pipeline run by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PipelineRun"
                ],
                "summary": "Delete pipeline run by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/project-groups": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get project group by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectGroup"
                ],
                "summary": "Get project group by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "member",
                        "name": "member",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create project group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectGroup"
                ],
                "summary": "Create project group",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ProjectGroup"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/project-groups/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get project group by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectGroup"
                ],
                "summary": "Get project group by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update project group by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectGroup"
                ],
                "summary": "Update project group by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ProjectGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete project group by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectGroup"
                ],
                "summary": "Delete project group by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/projects": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get projects by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Get projects by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "member",
                        "name": "member",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "project_group_id",
                        "name": "project_group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "repository_url",
                        "name": "repository_url",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Project"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/projects/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get project by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Get project by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update project by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Update project by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Project"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete project by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Delete project by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/tests": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get tests by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get tests by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pipeline_run_id",
                        "name": "pipeline_run_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tool_type_id",
                        "name": "tool_type_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Create test",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Test"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/tests/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get test by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get test by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update test by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Update test by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.Test"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete test by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Delete test by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/tool-types": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get tool types by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ToolType"
                ],
                "summary": "Get tool types by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "api_key",
                        "name": "api_key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create tool type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ToolType"
                ],
                "summary": "Create tool type",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ToolType"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/tool-types/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get tool type by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ToolType"
                ],
                "summary": "Get tool type by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update tool type by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ToolType"
                ],
                "summary": "Update tool type by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ToolType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete tool type by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ToolType"
                ],
                "summary": "Delete tool type by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get users by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get users by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pipeline_run_id",
                        "name": "pipeline_run_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tool_type_id",
                        "name": "tool_type_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization Token": []
                    }
                ],
                "description": "Get user by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_res.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_err.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "http_res.HTTPResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "data_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "users.Finding": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "cwe": {
                    "type": "integer"
                },
                "duplicate": {
                    "type": "boolean"
                },
                "dynamic_finding": {
                    "type": "boolean"
                },
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "impact": {
                    "type": "string"
                },
                "line": {
                    "type": "integer"
                },
                "mitigation": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                },
                "reference": {
                    "type": "string"
                },
                "risk_accepted": {
                    "type": "boolean"
                },
                "risk_description": {
                    "type": "string"
                },
                "severity": {
                    "type": "integer"
                },
                "static_finding": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "unique_id_from_tool": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "vuln_id_from_tool": {
                    "type": "string"
                }
            }
        },
        "users.PipelineEvaluation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "severity_critical_score": {
                    "type": "integer"
                },
                "severity_high_score": {
                    "type": "integer"
                },
                "severity_low_score": {
                    "type": "integer"
                },
                "severity_medium_score": {
                    "type": "integer"
                },
                "threshold_score": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "users.PipelineRun": {
            "type": "object",
            "properties": {
                "branch_name": {
                    "type": "string"
                },
                "commit_hash": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pipeline_run_id": {
                    "type": "integer"
                },
                "pipeline_run_url": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "users.Project": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_evaluation_id": {
                    "type": "integer"
                },
                "project_group_id": {
                    "type": "integer"
                },
                "repository_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "users.ProjectGroup": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "users.Test": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_run_id": {
                    "type": "integer"
                },
                "tool_type_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "users.ToolType": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "users.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "API REST in Golang with Gin Framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
